---

  - name: Setup development environment
    hosts: 
      - staging
      - production
    become: true
    become_user: root
    tasks:
      - name: Configuring environment on ArchLinux
        block:
          - name: Init and populate keys
            ansible.builtin.shell:
              cmd: pacman-key --init && pacman-key --populate
          - name: Upgrade keyring
            ansible.builtin.shell:
              cmd: pacman --noconfirm -Sy archlinux-keyring
          - name: Update repos and system
            ansible.builtin.shell:
              cmd: pacman -Syyu --noconfirm
          - name: Install packages
            community.general.pacman:
              update_cache: true
              name:
                - mariadb
                - mariadb-libs
                - jsoncpp
                - cronie
              state: latest
          - name: Install MariaDB
            ansible.builtin.shell:
              cmd: mariadb-install-db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
          - name: Start MariaDB service
            ansible.builtin.service:
              name: mariadb
              state: started
              enabled: true
          - name: Copy database template
            ansible.builtin.copy:
              src: database.sql
              dest: /home/arch/db.sql
              owner: arch
              mode: 644
          - name: Create database from template
            ansible.builtin.shell:
              cmd: mysql -u root < /home/arch/db.sql
          - name: Configure database root password for application
            ansible.builtin.shell:
              cmd: mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'qwerty'"
          - name: Configure cron for automatic backup of database
            ansible.builtin.copy:
              src: crontab
              dest: /etc/
              owner: root
              mode: 644
          - name: Start cronie service
            ansible.builtin.service:
              name: cronie
              state: started
              enabled: true
          - name: Copy jenkins key to production
            ansible.posix.authorized_key:
              user: arch
              state: present
              key: "{{ lookup('file', '../jenkins_prod.pub') }}"
            when: inventory_hostname in groups['production']
          - name: Copy jenkins key to dev
            ansible.posix.authorized_key:
              user: arch
              state: present
              key: "{{ lookup('file', '../jenkins_dev.pub') }}"
            when: inventory_hostname in groups['staging']
          - name: Enable pubkey authentication
            ansible.builtin.shell:
              cmd: echo 'PubkeyAuthentication yes' >> /etc/ssh/sshd_config
          - name: Enable ssh-rsa authentication
            ansible.builtin.shell:
              cmd: echo 'PubkeyAcceptedKeyTypes=+ssh-rsa' >> /etc/ssh/sshd_config
          - name: Restart machines for applying changes
            ansible.builtin.reboot:
          - name: Create project directory
            ansible.builtin.file:
              path: /home/arch/final-project
              owner: arch
              group: arch
              state: directory
        when: ansible_os_family == "Archlinux"
