---

  - name: Setup jenkins environment
    hosts: jenkins
    become: true
    become_user: root
    tasks:
      - name: Installation, configuration and starting jenkins environment on ArchLinux
        block:
          - name: Init and populate keys
            ansible.builtin.shell:
              cmd: pacman-key --init && pacman-key --populate
          - name: Upgrade keyring
            ansible.builtin.shell:
              cmd: pacman --noconfirm -Sy archlinux-keyring
          - name: Update repos and system
            ansible.builtin.shell:
              cmd: pacman -Syyu --noconfirm
          - name: Install jenkins
            community.general.pacman:
              update_cache: true
              name:
                - jenkins
                - fontconfig
                - ttf-dejavu
                - git
                - rsync
              state: latest
          - name: Fix configuration
            copy:
              src: ./jenkins.conf
              dest: /etc/conf.d/jenkins
              owner: root
              mode: 644
          - name: Copy jenkins backup to server
            ansible.posix.synchronize:
              src: ../jenkins/
              dest: /var/lib/jenkins
          - name: Make directory owned by jenkins
            ansible.builtin.shell:
              cmd: chown -R jenkins:jenkins /var/lib/jenkins
          - name: Install docker
            community.general.pacman:
              name:
                - docker
          - name: Create directory for Dockerfile
            ansible.builtin.file:
              name: /home/arch/docker
              state: directory
              owner: arch
              group: arch
          - name: Copy build agent Dockerfile
            ansible.builtin.copy:
              src: ../docker/Dockerfile
              dest: /home/arch/docker
              owner: arch
              mode: 644
          - name: Start docker daemon
            ansible.builtin.service:
              name: docker
              enabled: true
          - name: Reboot to start docker # needs to avoid start error
            ansible.builtin.reboot:
          - name: Build docker image for build stage
            ansible.builtin.shell:
              cmd: docker build -t build-container:1 /home/arch/docker/
          - name: Add jenkins to docker group
            ansible.builtin.shell:
              cmd: usermod -aG docker jenkins
          - name: Start jenkins service
            ansible.builtin.service:
              name: jenkins
              state: started
              enabled: true

        when: ansible_os_family == "Archlinux"
